language: node_js
node_js:
  - "10.16"
install:
  - npm --prefix ./client install
  - npm --prefix ./client run build
  - git add -f ./client/build
  - git commit -am ./client/build
  - npm install
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $ACCESS_KEY_ID
  secret_access_key:
    secure: $SECRET_KEY
  region: "ap-northeast-2"
  app: "volroom"
  env: "volroom"